### ISSUE TITLE
label_1geotiff_crf.py issue

### ISSUE THREAD

**Issue by mjcashman-usgs** [dbuscombe-usgs/dl_tools#9]
When labeling geotiffs using label_1geotiff_crf.py, I'm running into AttributeError: 'DatasetReader' object has no attribute 'get_crs'. 

Heres's the whole traceback:
> Traceback (most recent call last):
>   File "label_1geotiff_crf.py", line 343, in <module>
>     img, bs = read_geotiff(image_path)
>   File "label_1geotiff_crf.py", line 70, in read_geotiff
>     crs = src.get_crs()
> AttributeError: 'DatasetReader' object has no attribute 'get_crs'
 
I realize there is a comment about this in the code, but am putting this here for other's visibility/tracking. Any workarounds for the time being?

**Comment by dbuscombe-usgs** [comment]
just got to this! Fix is:

```
crs = src.crs
```
